# 定义数据库信息
SQLALCHEMY_DATABASE_URI = ''
SQLALCHEMY_POOL_RECYCLE = 3600
SQLALCHEMY_POOL_SIZE = 1000
SQLALCHEMY_MAX_OVERFLOW = -1
SQLALCHEMY_POOL_TIMEOUT = 120
SQLALCHEMY_TRACK_MODIFICATIONS = False

# 定义flask信息
SECRET_KEY = ''

# 定义celery信息
BROKER_URL = ''

CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = 'Asia/Shanghai'

# 定义微信公众平台信息
AppID = ''
AppSecret = ''
token = ''
